function [Dmat] = ThreeDFEgetDmat(materials, elmatnum)

if materials(elmatnum).typ == 'HookesMat'
    E = materials(elmatnum).E;
    nu = materials(elmatnum).nu;
    Dmat = E/((1+nu)*(1-2*nu))*[1-nu   nu   nu  0   0   0 ; ...
                                nu   1-nu   nu  0   0   0 ; ...
                                nu   nu   1-nu  0   0   0 ; ...
                                0   0   0  0.5-nu   0   0 ; ...
                                0   0   0  0    0.5-nu  0 ; ...
                                0   0   0  0    0   0.5-nu ];
end